# Generated by Django 6.1.1 on 2026-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
    ]
